
import Link from 'next/link';
import './globals.css';

export const metadata = {
    title: 'My App',
    description: 'Generated by Next.js',
};

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
        <body>
        <nav style={{ padding: '1rem', background: '#eee' }}>
            <Link href="/admin/login/pages/dashboard" style={{ marginRight: '1rem' }}>Dashboard</Link>
            <Link href="/admin/login/pages/company-events" style={{ marginRight: '1rem' }}>Company Events</Link>
            <Link href="/admin/login/pages/job-applications" style={{ marginRight: '1rem' }}>Job Application</Link>
            <Link href="/admin/login/pages/job-opportunities" style={{ marginRight: '1rem' }}>Job Opportunities</Link>
            <Link href="/admin/login/pages/news-feed" style={{ marginRight: '1rem' }}>News Feed</Link>
            <Link href="/admin/login/pages/projects" style={{ marginRight: '1rem' }}>Project</Link>

        </nav>
        <main>{children}</main>
        </body>
        </html>
    );
}
