// app/layout.tsx
import "tailwindcss";
import Sidebar from "@/app/admin/login/components/Layout/Sidebar"; // Adjust path as needed

export const metadata = {
  title: "My App",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex h-screen">
        <main className="flex-1 p-6 overflow-y-auto bg-gray-100">
          <Sidebar />
          {children}
        </main>
      </body>
    </html>
  );
}
